### ISSUE TITLE
No text for questions 

### ISSUE THREAD

**Issue by bretterer** [gruntjs/grunt-init-jquery#10]
I am using iTerm and oh my zsh.   when running grunt-init jquery in an empty folder.   the please answer the following: section does not have any text for the questions...  See image

![screen shot 2013-06-14 at 3 37 21 pm](https://f.cloud.github.com/assets/1906920/656375/fdea2eec-d529-11e2-900f-fa31ac3ffa34.png)

Please help me what to do...  I just did the git clone that is in readme today...

**Comment by shama** [comment]
This is because the solarized dark theme made bright black the same as the background. See gruntjs/grunt#181

Just tweak the colors as described in this comment: https://github.com/gruntjs/grunt/issues/181#issuecomment-5746654

**Comment by bretterer** [comment]
That was it... Thanks!
