### ISSUE TITLE
use grunt-init /path/to/template

### ISSUE THREAD

**Issue by tobeyouth** [gruntjs/grunt-init-jquery#13]
use  
`grunt-init /path/to/template`

error:
Fatal error: A valid init template name must be specified.

how to valid template name?

use rename.json?

**Comment by shama** [comment]
Check out the docs here: http://gruntjs.com/project-scaffolding

`/path/to/template` is intended to be actual path to a template or a name of a template in your `~/.grunt-init/` folder.
