### ISSUE TITLE
Fatal error: Arguments to path.join must be strings

### ISSUE THREAD

**Issue by hkdobrev** [gruntjs/grunt-init-jquery#14]
After running `grunt-init --force --stack jquery` and answering questions here's what I got:

```
Writing .gitignore...OK
Writing .jshintrc...OK
Writing CONTRIBUTING.md...OK
Writing Gruntfile.js...OK
Writing README.md...OK
Writing libs/jquery-loader.js...OK
Writing libs/jquery/jquery.js...OK
Writing libs/qunit/qunit.css...OK
Writing libs/qunit/qunit.js...OK
Writing src/.jshintrc...OK
Writing src/eyeline.js...OK
Writing test/.jshintrc...OK
Writing test/eyeline.html...OK
Writing test/eyeline_test.js...OK
Fatal error: Arguments to path.join must be strings
TypeError: Arguments to path.join must be strings
    at path.js:360:15
    at Array.filter (native)
    at Object.exports.join (path.js:358:36)
    at Object.file.isPathAbsolute (/usr/local/lib/node_modules/grunt-init/node_modules/grunt/lib/grunt/file.js:397:28)
    at Object.grunt.util._.extend.copy (/usr/local/lib/node_modules/grunt-init/tasks/init.js:343:25)
    at /usr/local/lib/node_modules/grunt-init/tasks/init.js:381:16
    at Array.forEach (native)
    at Object.grunt.util._.extend.copyAndProcess (/usr/local/lib/node_modules/grunt-init/tasks/init.js:367:28)
    at /Users/hkdobrev/.grunt-init/jquery/template.js:73:10
    at /usr/local/lib/node_modules/grunt-init/tasks/lib/prompt.js:124:13
```

**Comment by vladikoff** [comment]
Hey @hkdobrev !
What node, npm versions are you running? What OS?
i.e

```
~/tmp/tmp152/grunt-init-jquery on master*
$ node --version
v0.10.21
~/tmp/tmp152/grunt-init-jquery on master*
$ npm --version
1.3.11
```

**Comment by hkdobrev** [comment]
``` bash
$ node --version
v0.10.22

$ npm --version
1.3.14
```

Mac OS Mavericks 10.9.

**Comment by hkdobrev** [comment]
From what I see `filesToCopy` is creating a `files` array which contains a non-string value. It crashes later when [`copyAndProcess()`](https://github.com/gruntjs/grunt-init-jquery/blob/master/template.js#L73) and [`isPathAbsolute()`](https://github.com/gruntjs/grunt-init/blob/master/tasks/init.js#L381) are called.

**Comment by mansona** [comment]
I've just come across this too

```
vagrant@precise64:/apps/ui-framework$ node --version
v0.10.1
vagrant@precise64:/apps/ui-framework$ npm --version
1.2.15
vagrant@precise64:/apps/ui-framework$ uname -a
Linux precise64 3.2.0-40-generic #64-Ubuntu SMP Mon Mar 25 21:22:10 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
vagrant@precise64:/apps/ui-framework$ 
```

That's ubuntu 12.04

**Comment by jamesplease** [comment]
Hmm, I can't reproduce this. If y'all upgrade to the latest versions of npm & node do you still get the error?

`npm install npm -g`

`nvm install v0.10.26`

**Comment by jamesplease** [comment]
@hkdobrev, I'm also on OSX 10.9, and tried with your version of node and npm and still didn't get the error. Are you still getting it?

**Comment by mansona** [comment]
Sorry guys, I think i worked around the issue so I can't verify. I think it is safe to assume that the NPM version was the cause since i was quite far out of date. I would call for closing this issue. I'm going to unsubscribe because I'm not any help here to anyone

**Comment by hkdobrev** [comment]
Everything is OK now. Thanks!

**Comment by soundasleep** [comment]
This stlil occured for me on Windows 7 x64, node v0.10.26, npm 1.4.4.

Debugging showed that I was specifying an invalid license ("GPL" or "GPLv3") - valid licenses are listed in https://github.com/gruntjs/grunt-init/tree/master/templates/licenses (e.g. "GPL-2.0").
