### ISSUE TITLE
Fatal error in Windows even if the template is installed correctly

### ISSUE THREAD

**Issue by jubstuff** [gruntjs/grunt-init-jquery#6]
I've installed node.js via .msi and grunt-cli, grunt-init via npm. Then cloned this repo in %USER_PROFILE%/grunt-init.

But when I try to create a new project here's what I am getting:

```
C:\Users\Name\jqueryGrunt>grunt-init jquery
Running "init:jquery" (init) task
Loading "jquery" init template...ERROR

A valid init template name must be specified.

Available templates
 grunt-init-jquery  Create a jQuery plugin, including QUnit unit tests.

Templates that exist in the C:\Users\Just\.grunt-init directory may be run with
"grunt-init TEMPLATE". Templates that exist in another location may be run with
"grunt-init /path/to/TEMPLATE". A template is a directory that must contain, at
the very minimum, a template.js file.

For more information, see http://gruntjs.com/project-scaffolding

Fatal error: A valid init template name must be specified.

C:\Users\Name\jqueryGrunt>
```

Here is node.js version

```
>node -v
v0.10.0
```

**Comment by shama** [comment]
Take a look at this part:

```
Available templates
 grunt-init-jquery  Create a jQuery plugin, including QUnit unit tests.
```

I'm guessing it was cloned to `grunt-init-jquery` folder instead of just `jquery`. So it would expect `grunt-init grunt-init-jquery` to load that template. Instead rename that template folder to just `jquery`.

**Comment by giannwilk** [comment]
Im having this issue too, except under "Available templates" it list
jquery creat a Jquery plugin, including QUnit unit test.

then I get a fatal error.

Im using Command Prompt for Windows Xp
 Node version
V0.10.21

grunt version
grunt-cli v.0.1.13
grunt v0.4.0-rc8
