### ISSUE TITLE
generated _.jquery.json  does not match specs

### ISSUE THREAD

**Issue by zachofalltrades** [gruntjs/grunt-init-jquery#7]
'repository' is not one of the fields for the _.jquery.json file
The GitHub API provides the repository location when it does the "Post-Receive Hook"
http://plugins.jquery.com/docs/publish/

The 'download' field is neither output nor prompted for, but somehow the init script generates download links on the README.md file. It would be nice to make that consistent.

'keywords' (optional) is output as an empty array --there is no prompt to populate it

other fields that could be added, even if empty (so that the project owner could at least see that there are some blanks that could be filled in)
  'docs' (optional) no output, no prompt
  'demo' (optional) no output, no prompt
  'maintainers' (optional) no output, no prompt

jQuery plugin specs http://plugins.jquery.com/docs/package-manifest/

**Comment by hkdobrev** [comment]
:+1:

**Comment by sindresorhus** [comment]
PR welcome ;)

**Comment by hkdobrev** [comment]
@sindresorhus I am planning a lot of PRs for the template, but #14 is a bit of a blocker for me.

**Comment by jamesplease** [comment]
ping @hkdobrev

**Comment by arthurvr** [comment]
This issue can be closed. The jQuery plugins registry is currently in "read-only" mode.

**Comment by arthurvr** [comment]
And in fact, these files can be removed.
